# Site settings
title: Ayhan Oruc | Crafting concepts into realities
email: 
description: "Crafting concepts into realities"
baseurl: ""
url: "https://ayhanoruc.github.io/"

theme: minima
minima:
  skin: dark
