# Site settings
title: Ayhan Oruc | Crafting concepts into realities
email: 
description: "Crafting concepts into realities"
baseurl: ""
url: "https://ayhanoruc.github.io/"
paginate: 5


remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
  # - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
